Compatibility with alternative mailable syntax
mailersend/mailersend-laravel-driver pull request #35
Opened 2023-08-28 08:50 UTC by PeterOcansey

resolves #21

- [ ] Update README with new mailable syntax

2023-08-28 10:53 UTC, fosron commented on composer.json
> +        "php": "^8.0 || ^8.1",
thats is not the way to do it https://getcomposer.org/doc/articles/composer-platform-dependencies.md

2023-08-28 10:56 UTC, fosron requested changes
mentioning 8.x and 9.x is not really a good way to mention it, we should name it as old and new syntax maybe, or just use the terminology that laravel uses

2023-08-28 13:52 UTC, PeterOcansey commented
Old heading text
<img width="793" alt="Screenshot 2023-08-28 at 1 45 57 PM" src="https://github.com/mailersend/mailersend-laravel-driver/assets/52463144/91ced257-51ef-494b-a2e9-fe548fc81b23">

New heading text
<img width="782" alt="Screenshot 2023-08-28 at 1 46 33 PM" src="https://github.com/mailersend/mailersend-laravel-driver/assets/52463144/ed705c2c-351e-45ae-bc8b-be5434a973ca">

2023-08-28 13:59 UTC, PeterOcansey commented
This should cut it? cc @fosron

2023-08-28 15:03 UTC, fosron commented
@PeterOcansey let me think about it. We might skip the old syntax all together.

2023-10-19 11:31 UTC, l-alexandrov commented
Any updates on this?

2023-11-17 11:50 UTC, fosron commented
Tested the alternate syntax, works ok.

2023-11-17 11:50 UTC, fosron approved these changes

2023-11-17 11:50 UTC, merged